//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCollabro.BAL.Entities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eCollabroEntities : DbContext
    {
        public eCollabroEntities()
            : base("name=eCollabroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<ApprovalQueue> ApprovalQueues { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogCategory> BlogCategories { get; set; }
        public virtual DbSet<CodeFormat> CodeFormats { get; set; }
        public virtual DbSet<ContentComment> ContentComments { get; set; }
        public virtual DbSet<ContentLikeDislike> ContentLikeDislikes { get; set; }
        public virtual DbSet<ContentPage> ContentPages { get; set; }
        public virtual DbSet<ContentPageCategory> ContentPageCategories { get; set; }
        public virtual DbSet<ContentPermission> ContentPermissions { get; set; }
        public virtual DbSet<ContentRating> ContentRatings { get; set; }
        public virtual DbSet<ContentSetting> ContentSettings { get; set; }
        public virtual DbSet<ContentVote> ContentVotes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentLibrary> DocumentLibraries { get; set; }
        public virtual DbSet<EmailConfiguration> EmailConfigurations { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<FeatureContentSetting> FeatureContentSettings { get; set; }
        public virtual DbSet<FeaturePermission> FeaturePermissions { get; set; }
        public virtual DbSet<FileObject> FileObjects { get; set; }
        public virtual DbSet<ImageGallery> ImageGalleries { get; set; }
        public virtual DbSet<ImageObject> ImageObjects { get; set; }
        public virtual DbSet<lkpContext> lkpContexts { get; set; }
        public virtual DbSet<lkpLanguage> lkpLanguages { get; set; }
        public virtual DbSet<lkpNavigationType> lkpNavigationTypes { get; set; }
        public virtual DbSet<lkpProductType> lkpProductTypes { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Navigation> Navigations { get; set; }
        public virtual DbSet<OrderCart> OrderCarts { get; set; }
        public virtual DbSet<OrderCartItem> OrderCartItems { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleFeature> RoleFeatures { get; set; }
        public virtual DbSet<RoleFeaturePermission> RoleFeaturePermissions { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SiteCollectionAdmin> SiteCollectionAdmins { get; set; }
        public virtual DbSet<SiteConfiguration> SiteConfigurations { get; set; }
        public virtual DbSet<SiteContentSetting> SiteContentSettings { get; set; }
        public virtual DbSet<SiteFeature> SiteFeatures { get; set; }
        public virtual DbSet<SiteImage> SiteImages { get; set; }
        public virtual DbSet<UserMembership> UserMemberships { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserTask> UserTasks { get; set; }
        public virtual DbSet<WorkflowComment> WorkflowComments { get; set; }
    }
}
