//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCollabro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eCollabro.Resources.CoreValidationMessages", typeof(CoreValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has already been verified/confirmed. .
        /// </summary>
        public static string AccountAlreadyVerified {
            get {
                return ResourceManager.GetString("AccountAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has not been approved or active. Please try later..
        /// </summary>
        public static string AccountNotApproved {
            get {
                return ResourceManager.GetString("AccountNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has not been verified yet. Please verify your account..
        /// </summary>
        public static string AccountNotConfirmed {
            get {
                return ResourceManager.GetString("AccountNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At-least one Site Collection Admin required to be there in system..
        /// </summary>
        public static string AtleastOneSiteCollectionAdminRequired {
            get {
                return ResourceManager.GetString("AtleastOneSiteCollectionAdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCollabro has already been setup and configured..
        /// </summary>
        public static string eCollabroAlreadySetup {
            get {
                return ResourceManager.GetString("eCollabroAlreadySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not available or enabled for the selected site..
        /// </summary>
        public static string FeatureNotAssignedToSite {
            get {
                return ResourceManager.GetString("FeatureNotAssignedToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameters and not given. {0}.
        /// </summary>
        public static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password reset token or token has expired..
        /// </summary>
        public static string InvalidPasswordResetToken {
            get {
                return ResourceManager.GetString("InvalidPasswordResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Credentials. User details does not match or not exist in system..
        /// </summary>
        public static string InvalidUserCredentials {
            get {
                return ResourceManager.GetString("InvalidUserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Verification Token..
        /// </summary>
        public static string InvalidVerificationToken {
            get {
                return ResourceManager.GetString("InvalidVerificationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist or not marked as active..
        /// </summary>
        public static string RecordNotExistOrInactive {
            get {
                return ResourceManager.GetString("RecordNotExistOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not exist!.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration on Site not allowed. Please contact Administrator for request to create account..
        /// </summary>
        public static string SiteRegistrationNotAllowed {
            get {
                return ResourceManager.GetString("SiteRegistrationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected record is system defined and cannot be deleted or modified. {0}.
        /// </summary>
        public static string SystemDefinedValue {
            get {
                return ResourceManager.GetString("SystemDefinedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not has sufficient permissions to perform this operation. .
        /// </summary>
        public static string UnAuthorized {
            get {
                return ResourceManager.GetString("UnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked due to security resons for unauthorized attemps for more than allowed attempts. Please try resetting your password by clicking forget Password..
        /// </summary>
        public static string UserAccountLocked {
            get {
                return ResourceManager.GetString("UserAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist by the given credentials. .
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected user is not assigned to current site..
        /// </summary>
        public static string UserNotAssignedToSite {
            get {
                return ResourceManager.GetString("UserNotAssignedToSite", resourceCulture);
            }
        }
    }
}
